config/routes.rb
Rails.application.routes.draw do
  resources :documentos_simposios
  resources :videos_simposios
  resources :simposios
  resources :eventos
  resources :documentos
  
  
  get 'password_resets/new'

  get 'password_resets/edit'

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  get 'sessions/new'

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users
  resources :account_activations, only: [:edit]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  post '/lostemail', to: 'users#lostemail'
  
  patch 'editemailupdate' => 'users#editemailupdate'
  patch 'editpasswordupdate' => 'users#editpasswordupdate'
  
  patch 'addvideo' => 'videos_simposios#addvideo'
  patch 'adddoc' => 'documentos_simposios#adddoc'
  
  get 'dashboard' => 'pages#dashboard'
  get 'users_simposios' => 'pages#simposios'
  get 'user_aprove_image' => 'users#aprove_user_image'
  get 'aceitar_foto' => 'pages#aprovacao_imagens'
  get 'aceitar_doc' => 'documentos#aceitar_doc'
  get 'aprove_doc' => 'documentos#aprove_doc'
  get 'fotos' => 'users#fotos'
  get 'arquivo_show' => 'pages#arquivo_show'
  get 'editemail' => 'users#editemail'
  get 'editpassword' => 'users#editpassword'
  get 'recuperacao' => 'pages#recuperacao'
  get 'publicacoes'    => 'pages#publicacoes'
  get 'arquivos' => 'pages#arquivos'
  get 'tese_view' => 'pages#tese_view'
  get 'linhasdepesquisa'    => 'pages#linhasdepesquisa'
  get 'painel'    => 'pages#painel'
  get 'teses'    => 'pages#teses'
  get 'parceiros'    => 'pages#parceiros'
  get 'colaboradores' => 'pages#colaboradores'
  get 'instituicoes'  => 'pages#instituicoes'
  get 'events'    => 'pages#eventos'
  get 'coordenadores'    => 'pages#coordenadores'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

end

app/models/user.rb
class User < ApplicationRecord
    has_many :post, dependent: :destroy
    has_many :documento # dependent :destroy?
    has_many :eventos
    has_many :simposio
    
    
    attr_accessor :activation_token, :email_confirmation, :actual_password, :reset_token
            
    validate :email_match_email_confirmation, on: :create
    validate :new_email_match_email_confirmation, on: :update
    
    # chamada do método pra criar a activation_digest para futura confirmação de usuario
    # ocorre somente no ato de criação
    before_create :create_activation_digest
    before_save { self.email = email.downcase }
    
    # Validação 'nome'
    
    validates_presence_of :name
    validates :name, length: { minimum: 4, maximum: 40 }, 
                     allow_blank: true
    
    # Validação 'email' (retirei on update)
     VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates_presence_of :email
    validates :email, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }, 
                      allow_blank: true
    
    # Validação 'new_email' (retirei on update)
    
    validates :new_email, length: { maximum: 255 },
                          format: { with: VALID_EMAIL_REGEX },
                          uniqueness: { case_sensitive: false }, 
                          allow_blank: true
    
    # Validação 'matricula'
    
    validates_presence_of :matricula
    validates :matricula,  numericality: { only_integer: true }, 
                           length: { minimum: 5,  maximum: 15 },
                           allow_blank: true
    
    # Validação 'picture'
    
    validate :tamanho_imagem
    
    # Validação 'password'
    
      # Senha do tipo (deve conter letras e numeros, minimo 8, maximo 40)
    VALID_PASSWORD_REGEX = /(?=.*[a-zA-Z])(?=.*[0-9]).{8,40}/
    
    validates_presence_of :password, on: :create
    has_secure_password # bcrypt para manter a senha segura
    validates :password, format: { with: VALID_PASSWORD_REGEX, message: " deve possuir 8 caracteres, sendo pelo menos um numero e uma letra" },
                                 allow_blank: true
                         
  
    ##
    
    mount_uploader :picture, PictureUploader
    
    
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    
    def User.new_token
      SecureRandom.urlsafe_base64
    end
    
    def create_reset_digest
      self.reset_token = User.new_token
      update_attribute(:reset_digest,  User.digest(reset_token))
      update_attribute(:reset_sent_at, Time.zone.now)
    end
    
    def send_password_reset_email
      UserMailer.password_reset(self).deliver_now
    end
  
    # Retorna true se a token combina com o digest da confirmação 
    def authenticated?(token)
      digest = self.activation_digest
      return false  if digest.nil?
      # isso pode retornanar falso
      BCrypt::Password.new(digest).is_password?(token)
    end
    
    # Retorna true se a reset_token combina com o digest da confirmação 
    def reset_authenticated?(token)
      digest = self.reset_digest
      return false  if digest.nil?
      # isso pode retornanar falso
      BCrypt::Password.new(digest).is_password?(token)
    end
    
      # Activates an account.
    def activate
      update_attribute(:activated, true)
    end
  
    # Sends activation email.
    def send_activation_email
      UserMailer.account_activation(self).deliver_now
    end
    
    def send_update_activation_email
      UserMailer.update_activation(self).deliver_now
    end
    
    def update_activation_digest
      # Cria o token e usa criptografia
      self.activation_token  = User.new_token
      update_attribute(:activation_digest, User.digest(activation_token))
    end
    
    def password_reset_expired?
      reset_sent_at < 2.hours.ago
    end
  
    def foto_para_aprovar?
      if picture? and picture_accepted == false
        return true
      end
    end
  
  private 
  
    def tamanho_imagem
      if picture.size > (5/2).megabytes
        errors.add :picture, 'Imagem não pode ser maior que 2.5 Megabytes'
      end
    end
  
    def email_match_email_confirmation
      if email && email_confirmation
        unless email_confirmation == email 
          errors.add :email, '=> confirmação não combina'
        end
      end
    end
    
    def new_email_match_email_confirmation
      if new_email && email_confirmation
        unless email_confirmation == new_email
          errors.add :new_email, '=> confirmação não combina'
        end
        if User.find_by(:email => new_email)
          errors.add :new_email, '=> já está sendo usado'
        end
      end
    end
    
    def create_activation_digest
      # Cria o token e usa criptografia
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
    
    def aprova_foto
      if picture_accepted === false and picture != null
        picture_accepted = true
      end
    end
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :editemail, :editpassword]
  # Verifica se o usuario está logado
  before_action :authenticated_as_user, :only => [:index, :edit, :editemail, :editemailupdate, :editpassword, :editpasswordupdate, :update]
  # Verifica se é adm
  before_action :authenticated_as_admin, :only => [:destroy, :aprove_user_image]
  # Verifica se é adm ou current_user
  before_action :authenticated_as_admin_or_current_user, :only => [:index, :edit, :editemail, :editemailupdate, :editpassword, :editpasswordupdate]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end
  
  def lostemail
    
    user = User.find_by(email: params[:user][:email])
    user.update_activation_digest
    
    if user && !user.activated?
      if user.send_activation_email
        flash[:success] = 'E-mail enviado com sucesso'
        redirect_to root_url
      else
        flash[:danger] = 'Ocorreu um erro. Tente novamente mais tarde.'
        redirect_to recuperacao_url
      end
    else
      unless user
        flash[:danger] = 'E-mail inválido'
        redirect_to recuperacao_url
      else
        flash[:success] = 'E-mail já foi confirmado'
        redirect_to root_url
      end
    end
    
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end
  
  def fotos
  end
  

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
  
  def editemail
    if logged_in?
        @user = current_user
    end
  end
  
  def editemailupdate
    if logged_in?
      @user = current_user
    else
      @user = User.find(params[:id])
    end
    
    if @user && @user.authenticate(params[:user][:actual_password])
      respond_to do |format|
        if @user.update(user_params)
          @user.update_activation_digest
          @user.send_update_activation_email
          format.html { redirect_to @user, notice: 'Confirme seu novo e-mail' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :editemail }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      flash.now[:danger] = 'Senha inválida'
      render 'editemail'
    end
  end

  def editpassword
  end
  
  def editpasswordupdate
    if logged_in?
      @user = current_user
    else
      @user = User.find(params[:id])
    end
    if @user && @user.authenticate(params[:user][:actual_password])
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'Email was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :editpassword }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      flash.now[:danger] = 'Senha inválida' 
      render 'editpassword'
    end
  end
  
  # POST /users
  # POST /users.json
  def create
    
    @user = User.new(user_params)
    
    # força o usuario ficar com 'adm' falso a não ser que a pessoa criando seja adm
    if !administrador?
      @user.adm = false
    end
    
    respond_to do |format|
      if @user.save
        @user.send_activation_email
        format.html { redirect_to @user, notice: 'Confirme seu e-mail' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    
    
    
    respond_to do |format|
      if @user.update(user_params)
        if params[:user][:picture]
          @user.update(picture_accepted: false, picture_declined: false)
        end
        format.html { redirect_to @user, notice: 'Alterações efetuadas com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def aprove_user_image
    choice = params[:choice]
    user = User.find(params[:user_id])
    if (choice == 1)
      user.update(picture_accepted: true, picture_declined: false)
    else
      user.update(picture_accepted: false, picture_declined: true)
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if logged_in?
        @user = current_user
      else
         @user = User.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :adm, :matricula, :password, :password_confirmation, :email_confirmation, :picture, :actual_password, :new_email)
    end
    
    def authenticated_as_admin_or_current_user
    if !current_user.adm || @user != current_user
      flash.now[:error] = "Você não possui permissão para acessar essa pagina. Entre em contato com o administrador do dominio."
      redirect_to root_url
    end
  end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_changeemail.html.erb
<%= form_for(user, html: { multipart: true}, :url => {:action => "editemailupdate" , params: {id: @user.id}}) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :new_email %><br>
    <%= f.email_field :new_email, class:'form-control', :placeholder=>"Digite o E-mail"  %>
  </div>
  
  <div class="form-group">
     <%= f.label :email_confirmation %><br>
    <%= f.email_field :email_confirmation, class:'form-control', :placeholder=>"Confirme o E-mail" %>
  </div>
  
  <div class="form-group">
    <%= f.label :actual_password %><br>
    <%= f.password_field :actual_password, class:'form-control', :placeholder=>"Senha atual" %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Aplicar', class:'btn btn-default'%>
  </div>
<% end %>

app/views/users/_changepassword.html.erb
<%= form_for(user, html: { multipart: true}, :url => {:action => "editpasswordupdate" , params: {id: @user.id}}) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <!-- Senha antiga para provar que é o usuário antes de trocar a senha -->
  <div class="form-group">
    <%= f.label :actual_password %><br>
    <%= f.password_field :actual_password, class:'form-control', :placeholder=>"Digite a senha antiga"%>
  </div>
  
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password, class:'form-control', :placeholder=>"Digite a senha atual" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, class:'form-control', :placeholder=>"Confirme a senha" %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Alterar Senha', class:'btn btn-default'%>
  </div>
<% end %>

app/views/users/_editform.html.erb
<%= form_for(user, html: { multipart: true}) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control', :placeholder=>'digite seu nome' %>
  </div>
  
  <% if administrador? %>
    <div class="my-checkbox">
      <%= f.label :Administrador %><br>
      <%= f.check_box :adm, type:'checkbox'%>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula, class:'form-control', :placeholder=>"Digite a matrícula" %>
  </div>
  
  <span class="form-group">
    <%= f.file_field :picture %>
    <p class="help-block">Escolha uma boa foto.</p>
  </span>
  
  <div class="actions">
    <%= f.submit 'Aplicar Alterações', class:'btn btn-default'%>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user, html: { multipart: true}) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control', :placeholder=>'Digite seu nome' %>
  </div>
  
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.email_field :email, class:'form-control', :placeholder=>"Digite o E-mail" %>
  </div>
  
  <div class="form-group">
     <%= f.label :email_confirmation %><br>
    <%= f.email_field :email_confirmation, class:'form-control', :placeholder=>"Confirme o E-mail" %>
  </div>
  
  <% if administrador? %>
    <div class="my-checkbox">
      <%= f.label :Administrador %><br>
      <%= f.check_box :adm, type:'checkbox'%>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula, class:'form-control', :placeholder=>"Digite a matrícula" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password, class:'form-control', :placeholder=>"Digite a Senha" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, class:'form-control', :placeholder=>"Confirme a senha" %>
  </div>
  
 <span class="form-group">
    <%= f.file_field :picture %>
    <p class="help-block">Escolha uma boa foto.</p>
  </span>
  
  <div class="actions">
    <%= f.submit 'Criar', class:'btn btn-default'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if logged_in? %>
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Editar Usuário</h2>
      <div class="pst-container">
        <div class="pst-content">
          <div class="pst-form-user"><%= render 'editform', user: @user %></div>
        </div>
        <div class="pst-button">
          <%= link_to 'Visualizar', @user %> | 
          <%= link_to 'Alterar Senha', editpassword_path(:id => @user.id) %> | 
          <%= link_to 'Alterar e-mail', editemail_path(:id => @user.id) %> | 
          <%= link_to 'Voltar', users_path %>
        </div>
       </div>
    </div>  
  </div>
<%= render 'layouts/footer' %>
</div>
<% end %>

app/views/users/editemail.html.erb
<% if logged_in? %>
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Editar E-mail</h2>
      <div class="pst-container">
        <div class="pst-content">
          <div class="pst-form-user"><%= render 'changeemail', user: @user %></div>
        </div>
        <div class="pst-button">
          <%= link_to 'Visualizar', @user %> | 
          <%= link_to 'Voltar', users_path %>
        </div>
        <div class="pst-button">
          
        </div>
      </div>
    </div>  
  </div>
  <%= render 'layouts/footer' %>
</div>
<% end %>

app/views/users/editpassword.html.erb
<% if logged_in? %>
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Editar Senha</h2>
      <div class="pst-container">
        <div class="pst-content">
          <div class="pst-form-user"><%= render 'changepassword', user: @user %></div>
        </div>
        <div class="pst-button">
          <%= link_to 'Visualizar', @user %> | 
          <%= link_to 'Voltar', users_path %>
        </div>
        <div class="pst-button">
          
        </div>
      </div>
    </div>  
  </div>
  <%= render 'layouts/footer' %>
</div>
<% end %>

app/views/users/fotos.html.erb
<% if logged_in? %>
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Gerenciador de Fotos</h2>
      <div class="pst-container">
        <div class="pst-content">
          <div class="table-responsive">
            <table id="tablesorter" class="display" cellspacing="0" width="100%">
              <thead>
                <tr>
                  
                  <th>Nome</th>
                  <th>Email</th>
                  <th>Matricula</th>
                  <th>Aceitar</th>
                  <th>Negar</th>
                  
                </tr>
              </thead>
            
              <tbody>
                <% User.where(picture_accepted: false).find_each.each do |user| %>
                  <tr>
                    
                    <td><%= user.name %></td>
                    <td><%= user.email %></td>
                    <td><%= user.matricula %></td>
                    <td><%= link_to 'Aceitar', aceitar_foto_path(:aceitar => true, :id => user.id) %></td>
                    <td><%= link_to 'Negar', aceitar_foto_path(:aceitar => false, :id => user.id) %></td>
                  
                  </tr>
                <% end %>
              </tbody>  
            </table>
          </div>
        </div>
      </div>
    </div>  
  </div>
  <%= render 'layouts/footer' %>
</div>
<% end %>

app/views/users/index.html.erb
<% if logged_in? %>
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Gerenciador de Usuários</h2>
      <div class="pst-container">
        <div class="pst-content">
          <div class="table-responsive">
            <table id="tablesorter" class="display" cellspacing="0" width="100%">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Adm</th>
                  <th>Matricula</th>
                  <th>Activated?</th>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
            
              <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <td><%= user.name %></td>
                    <td><%= user.email %></td>
                    <td><%= user.adm %></td>
                    <td><%= user.matricula %></td>
                    <td><%= user.activated %></td>
                    <td><%= link_to 'Ver', user %></td>
                    <td><%= link_to 'Edit', edit_user_path(user) %></td>
                    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Você tem certeza disso?' } %></td>
                  </tr>
                <% end %>
              </tbody>  
            </table>
          </div>
        </div>
        <div class="pst-button">
          <button><%= link_to 'Novo Usuário', new_user_path %></button>
        </div>
      </div>
    </div>  
  </div>
  <%= render 'layouts/footer' %>
</div>
<% end %>

app/views/users/new.html.erb
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Novo Usuário</h2>
      <div class="pst-container">
        <div class="pst-content">
          <div class="pst-form-user"><%= render 'form', user: @user %></div>
        </div>
        <div class="pst-button">
          <%= link_to 'Voltar', users_path %>
        </div>
      </div>
    </div>  
  </div>
  <%= render 'layouts/footer' %>
</div>

app/views/users/show.html.erb
<% if logged_in? %>
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Usuário</h2>
      <div class="pst-container">
        <div class="pst-content">
          <div class="row">
            <div class="col-lg-6">
              <div class="p-img">
                <%= image_tag(@user.picture.url, class: 'img-responsive')if @user.picture? %>
                <%= image_tag('semfoto.jpg', class: 'img-responsive')if !@user.picture? %>
                <% if @user.picture && @user.picture_declined %>
                  <h4> Sua nova foto de perfil não foi aprovada. <br>
                      Tente novamente com uma foto diferente. </h4>
                <% end %>
                <% if @user.picture && !@user.picture_declined && !@user.picture_accepted %>
                  <h4> Sua foto ainda não foi aprovada. Você pderá vê-la, mas outros usuários não.</h4>
                <% end %>
              </div>
            </div>
            <div class="col-lg-6">
              <p><strong>Name:</strong><%= @user.name %></p>
              <p><strong>Email:</strong><%= @user.email %></p>
              <p><strong>Matricula:</strong><%= @user.matricula %></p>
            </div>
          </div>
        </div>
        <div class="pst-button">
          <%= link_to 'Editar', edit_user_path(@user) %>
          <%= link_to 'Voltar', users_path %>
        </div>
        <div class="pst-button">
          
        </div>
      </div>
    </div>  
  </div>
  <%= render 'layouts/footer' %>
</div>
<% end %>