config/routes.rb
Rails.application.routes.draw do
  resources :documentos_simposios
  resources :videos_simposios
  resources :simposios
  resources :eventos
  resources :documentos
  
  
  get 'password_resets/new'

  get 'password_resets/edit'

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  get 'sessions/new'

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users
  resources :account_activations, only: [:edit]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  post '/lostemail', to: 'users#lostemail'
  
  patch 'editemailupdate' => 'users#editemailupdate'
  patch 'editpasswordupdate' => 'users#editpasswordupdate'
  
  patch 'addvideo' => 'videos_simposios#addvideo'
  patch 'adddoc' => 'documentos_simposios#adddoc'
  
  get 'dashboard' => 'pages#dashboard'
  get 'users_simposios' => 'pages#simposios'
  get 'user_aprove_image' => 'users#aprove_user_image'
  get 'aceitar_foto' => 'pages#aprovacao_imagens'
  get 'aceitar_doc' => 'documentos#aceitar_doc'
  get 'aprove_doc' => 'documentos#aprove_doc'
  get 'fotos' => 'users#fotos'
  get 'arquivo_show' => 'pages#arquivo_show'
  get 'editemail' => 'users#editemail'
  get 'editpassword' => 'users#editpassword'
  get 'recuperacao' => 'pages#recuperacao'
  get 'publicacoes'    => 'pages#publicacoes'
  get 'arquivos' => 'pages#arquivos'
  get 'tese_view' => 'pages#tese_view'
  get 'linhasdepesquisa'    => 'pages#linhasdepesquisa'
  get 'painel'    => 'pages#painel'
  get 'teses'    => 'pages#teses'
  get 'parceiros'    => 'pages#parceiros'
  get 'colaboradores' => 'pages#colaboradores'
  get 'instituicoes'  => 'pages#instituicoes'
  get 'events'    => 'pages#eventos'
  get 'coordenadores'    => 'pages#coordenadores'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

end

app/views/pages/arquivos.html.erb
 
<div class="corpo-main-container">
    <div class='arquivos-main-container'>
        <div class="main wrapper clearfix">
            <h1>Arquivos</h1>
        <div class="pst-container">
            <div class="pst-content">
              <div class="table-responsive">
                <table id="tablesorter" class="display" cellspacing="0" width="100%">
                  <thead>
                      <tr>
                        <th>Mês</th>
                        <th>Nº de Publicações</th>
                      </tr>
                  </thead>
                  <tbody>
                      <% @datas_min.each do |data| %>
                        <tr>
                          <td><%= link_to imprime_data_arquivo(data) , arquivo_show_path(:month => data.month, :year => data.year) %></td>
                          <td><%= @data_freq.shift %></td>
                        </tr>
                      <% end %>
                  </tbody>
              </table>
              </div>
            </div>
          </div>
        </div>
    </div>
    
    
<%= render 'layouts/footer' %>
</div>
                

app/views/pages/dashboard.html.erb
<% provide(:title, "Dashboard") %>
<div class="corpo-main-container">
    <div class="dashboard-container">
        <div class="block">
            <div class="painel pp-main-container">
                <div class="main wrapper clearfix">
                    <h2>Painel de Controle</h2>
                    <div class="main wrapper clearfix">
                        <ul>
                           <li><%= link_to 'Eventos', events_path %></li>
                           <li><%= link_to 'Publicações', posts_path %></li>
                           <li><%= link_to 'Teses e Dissertações', teses_path %></li>
                           <li><%= link_to 'Simpósios', simposios_path %></li>
                           <li><%= link_to 'Usuários', users_path %></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="bemVindo pp-main-container">
                <div class="main wrapper clearfix">
                    <h3>Mensagem de Bem-vindo</h3>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ut quam odio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum consectetur, odio ultricies bibendum suscipit, lectus elit dignissim purus, eget mattis odio mi in mi. Nulla interdum libero mi, eget sodales urna rutrum eget. Nullam non neque nulla. Sed et lectus consequat, auctor purus at, laoreet risus. Aliquam commodo euismod tincidunt. Quisque ac lacus in justo luctus cursus non vel nulla. Sed ultricies vel risus.</p>
                </div>    
            </div>  
        </div>
     </div>
    <%= render 'layouts/footer' %>
    </div>
</div> 

app/views/pages/home.html.erb
 
<% provide(:title, "Home") %>
<div class="corpo-main-container">
    <div class="main-container">
        <div class="carrousel-container">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="">
                        <!-----------IMPLEMENTAR: carrousel *talvez------------->
                        <div class="swiper-container">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide"><div class="lp-img img-container-home"><%= image_tag("alunos.jpg", class: 'img-responsive') %></div></div>
                            <div class="swiper-slide"><div class="lp-img img-container-home"><%= image_tag("grupo.jpg", class: 'img-responsive') %></div></div>
                        </div>
                        <!-- Add Pagination -->
                    </div>
                	</div>	
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="c-title">
                        <div class="row">
                            <h3>BEM-VINDO AO LABPEC</h3>
                            <div class="main wrapper clearfix">
                                <div class="h-cadastro">
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled.</p>
                                    <button type="button" class="btn btn-danger btn-lg btn-cadastro ">
                                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true" style="margin-right:10px;"></span><% link_to login_url %>Cadastro</button>
                                        <button type="button" class="btn btn-success btn-lg btn-cadastro" data-toggle="modal" data-target="#myModal">
                                        <span class="glyphicon glyphicon-envelope" aria-hidden="true" style="margin-right:10px;"></span>Contato</button>
                                </div>
                            </div>
                        </div>  
                    </div>  
                
                </div>    
            </div>
        </div>    
        
    </div> 
    <div class="destaques-container">
        <div class="main wrapper clearfix">
            <h1>Destaques</h1>
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="c-simp">
                        <h2>XV Simpósio do lorem ipsum</h2>
                        <h4>Este é o simposio do lorem ipsum, feito anualmente pela sociedade lorem ipsum</h4>
                        <iframe width="100%" height="315" src="https://www.youtube.com/embed/ug5y2Uo1mPE" frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="main wrapper clearfix">
                        <!---VERIFICAR: uso do botão--->
                        <!---<button type="button" class="p-buttom">Enviar Publicação</button>-->
                        <div class="ps-main-container">
                           <h2>Mais Visto</h2>
                           <div class="row ps-content">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <h4>XV simpósio do lorem ipsum</h4>
                                    <iframe width="100%" height="115" src="https://www.youtube.com/embed/ug5y2Uo1mPE" frameborder="0" allowfullscreen></iframe>
                                </div>
                           </div>
                        </div>   
                    </div>    
                </div>
            </div>    
        </div>    
    </div>    
    <div class="main info-container">
        <div class="row">
            <div class="main wrapper clearfix">
                <div class="event col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div>    
                    <h1>Eventos</h1>
                    <!-----------IMPLEMENTAR: buscar eventos do BD------------->
                        <% @eventos.each do |evento| %>
                            <div class="row h-cald">
                                
                                <div class="r-borda-dotted rb-cal col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                    <h5><%= imprime_data(evento.data, 2) %></h5>
                                </div>
                                <div class="col-lg-8 col-md-8 col-sm-4 col-xs-12 d-event">
                                    <h4><%= link_to evento.titulo, evento %></h4>
                                    <p><%= evento.localizacao %></p>
                                </div>  
                            </div>
                        <%end %>
                    </div>    
                    <div class="h-link">
                        <%= link_to events_path do %><p>+ saiba mais</p> <% end %>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="ie-contato-container">    
                        <div class="contato">    
                            <h1>Contato</h1>
                            <p>Rua Professor Marcos Waldemar de Freitas Reis, 100 – bloco C</p>
                            <p>São Domingos, Niterói-RJ</p>
                            <p>CEP: 24210-201</p>
                            <p>Tel: +55 21 26292605</p>
                            <p>Fax: + 55 21 26292607</p>
                            <p>Email: uff.labpec@gmail.com</p>   
                        </div>    
                    </div>    
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="row ie-container">
                        <!-----------IMPLEMENTAR: buscar noticias do BD------------->
                        <h1>Publicações</h1>
                        <% @noticias.each do |n| %>
                        <div class="h-noticia b-borda-dotted ic-title p-info">
                            <h5><%= link_to n.titulo, n %> </h5>
                            <p><%= n.descricao %></p>
                        </div>
                        <% end %>
                    </div> 
                    <div class="h-link">
                        <p><%= link_to '+ saiba mais', publicacoes_path %></p>
                    </div>
                </div>
            </div>    
        </div>
    </div>
    <%= render 'layouts/footer' %>
</div>

<!--<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>-->

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Contato LABPEC</h4>
      </div>
      <div class="modal-body">
        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Email:</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="exampleInputMensagem">Mensagem:</label>
                <textarea class="form-control" rows="3" placeholder="Mensagem..."></textarea>
            </div>  
            <button type="submit" class="btn btn-default">Enviar</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/painel.html.erb
<% if logged_in? %>
<div class="pnl-corpo-main-container">
    <div class="pnl-main-container">
      <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading"><h3>Dashboard</h3></div>
      <div class="panel-body">
        <p>Seja bem vindo administrador! Use as opções abaixo para gerenciar os conteúdos do seu site. Caso tenha alguma dúvida, ou ocorra algum erro, por favor contactar os desenvolvedores em <strong>contato@injunior.com.br</strong></p>
      </div>
    
      <!-- List group -->
      <ul class="list-group">
        <li class="list-group-item">
          <div class="row">
            <div class="col-lg-4 col-md-4">
              <button type="button" class="btn pnl-button btn-success btn-lg btn-cadastro ">
                <%= link_to 'Usuarios', users_path %>
              </button> 
            </div>
            <div class="col-lg-8 col-md-8">
              <p>Gerencie aqui a área de usuários do site.</p>
            </div>
          </div>  
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-lg-4 col-md-4">
              <button type="button" class="btn pnl-button btn-danger btn-lg btn-cadastro ">
                <%= link_to 'Publicações', posts_path %>
              </button>
            </div>
            <div class="col-lg-8 col-md-8">
              <p>Gerencie aqui a área de postagens do site.</p>
            </div>
          </div>      
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-lg-4 col-md-4">
              <button type="button" class="btn pnl-button btn-info btn-lg btn-cadastro ">
                <%= link_to 'Documentos', documentos_path %>
              </button>  
            </div>  
            <div class="col-lg-8 col-md-8">  
              <p>Gerencie aqui a área de documentos do site.</p>
            </div>  
          </div>  
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-lg-4 col-md-4">
              <button type="button" class="btn pnl-button btn-warning btn-lg btn-cadastro ">
                <%= link_to 'Eventos', eventos_path %>
              </button>  
            </div>  
            <div class="col-lg-8 col-md-8">  
              <p>Gerencie aqui a área de eventos do site.</p>
            </div>  
          </div>  
        </li>
      </ul>
    </div>
      
    </div>
<%= render 'layouts/footer' %>
</div>
<% end %>

app/views/pages/publicacoes.html.erb
 
<% provide(:title, "Publicações") %>
<div class="corpo-main-container">
    <div class="publicacoes-container">
        <div class="pp-carrousel-container">
            <div class="">
                <div class="pp-carrousel">
                    <div class="swiper-container">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide"><%= image_tag("img6.jpg", class: 'pp-img img-responsive') %></div>
                            <div class="swiper-slide"><%= image_tag("img2.png", class: 'pp-img img-responsive') %></div>
                            <div class="swiper-slide"><%= image_tag("img5.jpg", class: 'pp-img img-responsive') %></div>
                        </div>
                        <!-- Add Pagination -->
                        <div class="swiper-pagination"></div>
                        <!-- Add Arrows -->
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                </div>    
            </div>
        </div>
        <div class="pp-main-container">
            <div class="main wrapper clearfix">
                <h1>Publicações</h1>
            
              <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                   <div class="main wrapper clearfix">
                        <% @posts.each do |publicacao| %>
                            <div class="row p-container">
                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                    <div class="p-img">
                                        <%= image_tag(publicacao.picture.url, class: 'img-responsive') if publicacao.picture? %>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                    <div class="p-info">
                                      <h3><%= link_to  publicacao.titulo, publicacao %></h3>
                                      <h6><%= imprime_data(publicacao.created_at) %> </h6>
                                      <p><%= publicacao.descricao %></p>
                                    </div>
                                </div>
                            </div>    
                        <% end %>
                        <%= will_paginate @posts %>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="main wrapper clearfix">
                        <!---VERIFICAR: uso do botão--->
                        <!---<button type="button" class="p-buttom">Enviar Publicação</button>-->
                        <div class="ps-main-container">
                           <h2>Mais Visto</h2>
                           <div class="row ps-content">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="p-img">
                                        <%= image_tag(@mais_visitado.picture.url, class: 'img-responsive') if @mais_visitado.picture? %>
                                    </div>
                                </div>
                                <div class="p-info col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="p-info">
                                        
                                        <h3><%= link_to @mais_visitado.titulo, @mais_visitado %></h3>
                                        <h6><%= imprime_data(@mais_visitado.created_at) %> </h6>
                                        <p><%=@mais_visitado.descricao %></p>
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>  
                    <!------IMPLEMENTAR: badge dinamicamente como atributo derivado--------->
                    <div class="main wrapper clearfix">
                        <div class="ps-main-container">
                            <h2>Arquivo</h2>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="r-arquivo">
                                        <% @datas_min.slice(0,4).each do |d| %>
                                          <div class="col-lg-12", style="padding-bottom: 14px"><%= link_to imprime_data_arquivo(d), arquivo_show_path(:month => d.month, :year => d.year) %>
                                          <span class="badge", style="margin-left: 5px"><%= @data_freq.shift%></span></div>
                                        <% end %>
                                    </div>
                                </div>    
                                <div class="col-lg-12">
                                    
                                    <div class="t-arquivo"><%= link_to 'Ver todos', arquivos_path %></div>
                                </div>
                            </div>
                        </div>
                    </div>    
                    <div class="main wrapper clearfix">
                        <div class="ps-main-container">
                            <h2>Busca</h2>
                            <div class="p-busca">
                                <div class="input-group">
                                  <%= form_for(:post, url: publicacoes_path, method: :get) do |f| %>
                                      <%= f.text_field :search, class: "form-control", :placeholder => 'Buscar por...' %>
                                      <span class="input-group-btn">
                                        <%= f.submit 'Buscar', class:'btn btn-default pp-btn'%>
                                      </span>
                                  <% end %>
                                </div>
                            </div>    
                        
                        </div>
                    </div>    
                </div>    
            </div> 
            </div>
        </div>    
    </div>
    <%= render 'layouts/footer' %>
</div> 

app/views/pages/recuperacao.html.erb
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
    <h2>Recuperar senha</h2>
      <div class="row">
        <div class="col-lg-6">
           <%= form_for(:password_reset, url: password_resets_path) do |f| %>
              <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>
              </div>
              <div class="actions">  
                <%= f.submit "Trocar minha senha", class: "btn" %>
              </div>
           <% end %>
          
           <p> Não recebi meu e-mail de confirmação </p>
           
           <%= form_for(:user, url: lostemail_path, html:{class:"form-contato"} ) do |f| %>
            
            <div class="form-group"
              <%= f.label :email %><br>
              <%= f.email_field :email, :value => "", class:'form-control' %>
            </div>
            
            <div class="actions">
              <%= f.submit 'Re-enviar confirmação', class:'btn'%>
            </div>
            
            <% end %>
          </div>
      </div>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</div>  

app/views/pages/teses.html.erb
 
<% provide(:title, "TDs") %>
<div class="corpo-main-container">
    <div class="td-container">
        <div class="td-main-container">
        <div class="main wrapper clearfix">
            <h1>Teses e Dissertações</h1>
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="main wrapper clearfix">
                        <!--<div class="row es-content">
                              <div class="col-md-12">
                                <div class="input-group" id="adv-search">
                                    <input type="text" class="form-control" placeholder="busca por tipo..." />
                                    <div class="input-group-btn">
                                        <div class="btn-group" role="group">
                                            <div class="dropdown dropdown-lg">
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></button>
                                                <div class="dropdown-menu dropdown-menu-right" role="menu">
                                                    <form class="form-horizontal" role="form">
                                                      <div class="form-group">
                                                        <label for="filter">Filtrar por</label>
                                                        <select class="form-control">
                                                            <option value="0" selected>Todos</option>
                                                            <option value="1">Teses</option>
                                                            <option value="2">Dissertações</option>
                                                            <option value="3">Mais visualizados</option>
                                                            <option value="4">Mais recentes</option>
                                                        </select>
                                                      </div>
                                                      <div class="form-group">
                                                        <label for="contain">Autor</label>
                                                        <input class="form-control" type="text" />
                                                      </div>
                                                      <div class="form-group">
                                                        <label for="contain">Contém as palavras</label>
                                                        <input class="form-control" type="text" />
                                                      </div>
                                                      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                                                    </form>
                                                </div>
                                            </div>
                                            <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                                        </div>
                                    </div>
                                </div>
                              </div>
                            </div> -->
                        <% @teses.each do |tese| %>
                        <div class="row td-e-container">
                            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                                <p><% if tese.author %>
                                    <%= tese.author %>
                                    <% end %></p>
                                <div class="td-img">
                                    <%= image_tag("semfoto.jpg", class: 'img-responsive') %>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="p-info">
                                  <h3><%= link_to tese.titulo, tese %></h3>
                                  <h6><%= imprime_data(tese.data_defesa, 0)%></h6>
                                  <p><%= tese.descricao%></p>
                                  <%= link_to "Download", tese.arquivo_url %>
                                </div>
                            </div>
                        </div> 
                        <% end %>
                        <%= will_paginate @teses %>
                        <div class="ts-button">
                            <button class="btn"><%= link_to 'Enviar Documento', new_documento_path %></button>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                  <div class="main wrapper clearfix">
                        <div class="ps-main-container">
                            <h2>Arquivo</h2>
                            <div class="row">
                                <div class="arq-peq col-lg-12">
                                    <div class="r-arquivo">
                                          <% @datas_min.slice(0,4).each do |d| %>
                                          <div class="col-lg-12", style="padding-bottom: 14px"><%= link_to imprime_data_arquivo(d), arquivo_show_path(:month => d.month, :year => d.year) %>
                                          <span class="badge", style="margin-left: 5px"><%= @data_freq.shift%></span></div>
                                        <% end %>
                                    </div>
                                </div>    
                                <div class="col-lg-12">
                                    
                                    <div class="t-arquivo"><%= link_to 'Ver todos', arquivos_path %></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="main wrapper clearfix">
                        <div class="ps-main-container">
                            <h2>Busca</h2>
                            <div class="p-busca">
                                <div class="input-group">
                                  <%= form_for(:tese, url: teses_path, method: :get) do |f| %>
                                      <%= f.text_field :search, class: "form-control", :placeholder => 'Buscar por...' %>
                                      <span class="input-group-btn">
                                        <%= f.submit 'Buscar', class:'btn btn-default pp-btn'%>
                                      </span>
                                  <% end %>
                                </div>
                            </div>    
                        
                        </div>
                        <div class="pco main wrapper clearfix">
                                <h3>Instituições Parceiras</h3>
                                  <%= image_tag("logo-capes.png", class: 'imgs img-responsive') %>
                                  <%= image_tag("viadrina_logo2.png", class: 'imgs img-responsive') %>
                                  <%= image_tag("logo uff.jpg", class: 'imgs img-responsive') %>
                                  <%= image_tag("daad pt al.png", class: 'imgs img-responsive') %>
                        </div>    
                        
                        </div>
                  </div>
                </div> 
                <div></div>
            </div>
        </div>
    </div>
    <%= render 'layouts/footer' %>
    </div>
</div>  