config/routes.rb
Rails.application.routes.draw do
  resources :documentos_simposios
  resources :videos_simposios
  resources :simposios
  resources :eventos
  resources :documentos
  
  
  get 'password_resets/new'

  get 'password_resets/edit'

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  get 'sessions/new'

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users
  resources :account_activations, only: [:edit]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  post '/lostemail', to: 'users#lostemail'
  
  patch 'editemailupdate' => 'users#editemailupdate'
  patch 'editpasswordupdate' => 'users#editpasswordupdate'
  
  patch 'addvideo' => 'videos_simposios#addvideo'
  patch 'adddoc' => 'documentos_simposios#adddoc'
  
  get 'dashboard' => 'pages#dashboard'
  get 'users_simposios' => 'pages#simposios'
  get 'user_aprove_image' => 'users#aprove_user_image'
  get 'aceitar_foto' => 'pages#aprovacao_imagens'
  get 'aceitar_doc' => 'documentos#aceitar_doc'
  get 'aprove_doc' => 'documentos#aprove_doc'
  get 'fotos' => 'users#fotos'
  get 'arquivo_show' => 'pages#arquivo_show'
  get 'editemail' => 'users#editemail'
  get 'editpassword' => 'users#editpassword'
  get 'recuperacao' => 'pages#recuperacao'
  get 'publicacoes'    => 'pages#publicacoes'
  get 'arquivos' => 'pages#arquivos'
  get 'tese_view' => 'pages#tese_view'
  get 'linhasdepesquisa'    => 'pages#linhasdepesquisa'
  get 'painel'    => 'pages#painel'
  get 'teses'    => 'pages#teses'
  get 'parceiros'    => 'pages#parceiros'
  get 'colaboradores' => 'pages#colaboradores'
  get 'instituicoes'  => 'pages#instituicoes'
  get 'events'    => 'pages#eventos'
  get 'coordenadores'    => 'pages#coordenadores'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

end

app/models/documento.rb
class Documento < ApplicationRecord
  belongs_to :user
  
#  validates_presence_of :cpf
#  validates_length_of :cpf, :is => 11, :allow_blank => true
#  validates_numericality_of :cpf, :allow_blank => true
#  validates_uniqueness_of :cpf, :allow_blank => true
#  validates_as_cpf :cpf, :allow_blank => true
  
  # Validação user_id
  
  validates_presence_of :user_id
  
  # Validação 'titulo'
  
  validates_presence_of :titulo
  validates :titulo, length: { minimum: 10, maximum: 90 }, 
                     allow_blank: true
  
  # Validação 'descricao'
  
  validates_presence_of :descricao
  validates :descricao, length: { minimum: 30, maximum: 250 }, 
                        allow_blank: true

  # Validação 'data_defesa'
  
   validates_presence_of :data_defesa
   validate :data_nao_esta_no_passado
  
  # Validação 'status' (checar defaults)
  
  validates_presence_of :status
  
  # Validação 'tese' (checar defaults)
  
  validates_presence_of :tese
  
  # Validação 'mestrado' (checar defaults)
  
  validates_presence_of :mestrado
  
  # Validação 'arquivo'
  
  validates_presence_of :arquivo
  validate :tamanho_do_arquivo
  
  # Validação 'accepted'
  
  validates_presence_of :accepted
  
  # Validação 'respondido'
  
  validates_presence_of :respondido
  
  ##
  
  mount_uploader :arquivo, FileUploader
  
  # Exclui documentos antigos que foram reprovados
  
  def self.destroy_docs_antigos_reprovados
    Documento.where('updated_at < ? and respondido = ? and accepted = ?', Time.now - 4.weeks , true, false).destroy_all
  end
  
  private
    def data_nao_esta_no_passado
      if !data_defesa.present?
        errors.add(:data_defesa, "O documento deve possuir uma data em que foi defendido")
        return
      end
      if data_defesa >= (Date.today + 1.day)
          errors.add(:data_defesa, "Experimente checar a data (está no futuro)")
      end
    end
    
    def tamanho_do_arquivo
      if arquivo.size > (3).megabytes
        errors.add :arquivo, 'O arquivo deve conter no máximo 3 megabytes.'
      end
    end
end

app/controllers/documentos_controller.rb
class DocumentosController < ApplicationController
  before_action :set_documento, only: [:show, :edit, :update, :destroy]
  # Verifica se o usuario está logado
  before_action :authenticated_as_user, :except => [:show]
  # Verifica se é adm
  before_action :authenticated_as_admin, :except => [:show, :new, :create]

  # GET /documentos
  # GET /documentos.json
  def index
    @documentos = Documento.all
  end

  # GET /documentos/1
  # GET /documentos/1.json
  def show
  end

  # GET /documentos/new
  def new
    @documento = Documento.new
  end

  # GET /documentos/1/edit
  def edit
  end
  
  def aceitar_doc
    @documentos = Documento.where(:respondido => false)
  end

  # POST /documentos
  # POST /documentos.json
  def create
    params[:documento][:user_id] = current_user.id
    @documento = Documento.new(documento_params)
    if (params[:documento][:tese] == "Tese")
      @documento.tese = true
    else
      @documento.tese = false
    end
    
    if (params[:documento][:mestrado] == "Mestrado")
      @documento.mestrado = true
    else
      @documento.mestrado = false
    end
    
    # Força o status do documento ser pendente por motivos de segurança
    @documento.accepted = false
    @documento.respondido = false
  
    respond_to do |format|
      if @documento.save
        format.html { redirect_to @documento, notice: 'Documento was successfully created.' }
        format.json { render :show, status: :created, location: @documento }
      else
        format.html { render :new }
        format.json { render json: @documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documentos/1
  # PATCH/PUT /documentos/1.json
  def update
    respond_to do |format|
      if @documento.update(documento_params)
        format.html { redirect_to @documento, notice: 'Documento was successfully updated.' }
        format.json { render :show, status: :ok, location: @documento }
      else
        format.html { render :edit }
        format.json { render json: @documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documentos/1
  # DELETE /documentos/1.json
  def destroy
    @documento.destroy
    respond_to do |format|
      format.html { redirect_to documentos_url, notice: 'Documento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def aprove_doc
    choice = params[:choice]
    doc = Documento.find(params[:doc_id])
    if (choice == "1")
      doc.update(accepted: true, respondido: true)
    else
      doc.update(accepted: false, respondido: true)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_documento
      @documento = Documento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def documento_params
      params.require(:documento).permit(:user_id, :titulo, :descricao, :status, :data_defesa, :tese, :mestrado, :arquivo, :author)
    end
    
  
  
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/views/documentos/_form.html.erb
<%= form_for(documento, html: { multipart: true})  do |f| %>

  <% if documento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(documento.errors.count, "error") %> prohibited this documento from being saved:</h2>

      <ul>
      <% documento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group">
    <%= f.label :titulo %>
    <%= f.text_field :titulo,  class:'form-control', :placeholder=>"Digite o título"  %>
  </div>
  
  <span class="counter"></span>
  
  <div class="form-group">
    <%= f.label :descricao %>
    <%= f.text_area :descricao,  class:'form-control', :placeholder=>"Digite a descrição" %>
  </div>
  
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_area :author,  class:'form-control', :placeholder=>"Digite o nome do Autor" %>
  </div>

  <div class="form-group">
    <%= f.label :data_defesa %>
    <%= f.date_select :data_defesa, class:'form-control' %>
  </div>
  
  <div class="form-group">
  <label>Tipo do documento</label><br>
    <%= f.select :tese, options_for_select(["Tese", "Dissertação"]) %>
  </div>
  
  <div class="form-group">
  <label>Categoria do documento</label><br>
    <%= f.select :mestrado, options_for_select(["Mestrado", "Doutorado"]) %>
  </div>
  
  <div class="form-group">
    <%= f.label :arquivo %>
    <%= f.file_field :arquivo %>
  </div>

  <div class="actions">
    <%= f.submit 'Enviar', class:'btn btn-default'%>
  </div>
<% end %>

app/views/documentos/_formedit.html.erb
<%= form_for(documento, html: { multipart: true})  do |f| %>

  <% if documento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(documento.errors.count, "error") %> prohibited this documento from being saved:</h2>

      <ul>
      <% documento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group">
    <%= f.label :titulo %>
    <%= f.text_field :titulo,  class:'form-control', :placeholder=>"Digite o título"  %>
  </div>
  
  <span class="counter"></span>
  
  <div class="form-group">
    <%= f.label :descricao %>
    <%= f.text_area :descricao,  class:'form-control', :placeholder=>"Digite a descrição" %>
  </div>
  
   <div class="form-group">
    <%= f.label :author %>
    <%= f.text_area :author,  class:'form-control', :placeholder=>"Digite o nome do Autor" %>
  </div>

  <div class="form-group">
    <%= f.label :data_defesa %>
    <%= f.date_select :data_defesa, class:'form-control' %>
  </div>
  
  <div class="form-group">
  <label>Tipo do documento</label><br>
    <%= f.select :tese, options_for_select(["Tese", "Dissertação"]) %>
  </div>

  <div class="actions">
    <%= f.submit 'Enviar', class:'btn btn-default'%>
  </div>
<% end %>

app/views/documentos/aceitar_doc.html.erb
<% provide(:title, "Documentos") %>
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Respostas de Documentos</h2>
      <div class="pst-container">
        <div class="pst-content">
          <div class="table-responsive">
            <table id="tablesorter" class="display" cellspacing="0" width="100%">
              <thead>
                <tr>
                  <th>Nome do Usuário</th>
                  <th>Título</th>
                  <th>Descrição</th>
                  <th>Tese/Dissertação</th>
                  <th>Mestrado/Doutorado</th>
                  <th>Download</th>
                  <th>Aceitar</th>
                  <th>Negar</th>
                </tr>
              </thead>
            
              <tbody>
                <% @documentos.each do |documento| %>
                  <tr>
                    <td>
                      <% if documento.user %>
                        <%= documento.user.name %>
                      <% end %>
                    </td>
                    <td><%= documento.titulo %></td>
                    <td><%= documento.descricao %></td>
                    <td>
                      <% if documento.tese %>
                        <%= "Tese" %>
                      <% else %>
                        <%= "Dissertação" %>
                      <% end %>
                    </td>
                    <td>
                      <% if documento.mestrado %>
                        <%= "Mestrado" %>
                      <% else %>
                        <%= "Doutorado" %>
                      <% end %>
                    </td>
                    <td><%= link_to "Download", documento.arquivo_url %></td>
                    <td id="aceitar_doc_<%= documento.id %>"><%= link_to 'Aceitar', aprove_doc_path(:choice => 1, :doc_id => documento.id), remote: true,
                    id: "link_aceita_doc_#{documento.id}"%></td>
                    <td id="negar_doc_<%= documento.id %>"><%= link_to 'Negar', aprove_doc_path(:choice => 2, :doc_id => documento.id), remote: true, 
                    id: "link_nega_doc_#{documento.id}" %></td>
                  </tr>
                  
                    <% content_for :js do %>
                      $('#link_aceita_doc_<%= documento.id %>').bind('ajax:success', function(){
                        $('#aceitar_doc_<%= documento.id %>').text('Aceito');
                        $('#negar_doc_<%= documento.id %>').text('Aceito');
                        
                        $('#aceitar_doc_<%= documento.id %>').addClass('aceito');
                        $('#negar_doc_<%= documento.id %>').addClass('aceito');
                        
                      });
                      
                      $('#link_nega_doc_<%= documento.id %>').bind('ajax:success', function(){
                        $('#aceitar_doc_<%= documento.id %>').text('Negado');
                        $('#negar_doc_<%= documento.id %>').text('Negado');
                        
                        $('#aceitar_doc_<%= documento.id %>').addClass('negado');
                        $('#negar_doc_<%= documento.id %>').addClass('negado');
                        
                      });
                    
                  <%end%>
                  
                <% end %>
              </tbody>
            </table>
            </div>
        </div>
        <div class="pst-button">
          <button><%= link_to 'Novo Documento', new_documento_path %></button>
        </div>
      </div>
    </div>  
  </div>
  <%= render 'layouts/footer' %>
</div>

            

app/views/documentos/edit.html.erb
<% if logged_in? %>
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Editar Documento</h2>
      <div class="pst-container">
        <div class="pst-content">
          <%= render 'formedit', documento: @documento %>
        </div>
        <div class="pst-button">
          <%= link_to 'Visualizar', @documento %> | <%= link_to 'Voltar', documentos_path %>
        </div>
      </div>
    </div>  
  </div>
  <%= render 'layouts/footer' %>
</div>

<% end %>

app/views/documentos/index.html.erb
<% provide(:title, "Documentos") %>
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Gerenciador de Documentos</h2>
      <div class="pst-container">
        <div class="pst-content">
          <div class="table-responsive">
            <table id="tablesorter" class="display" cellspacing="0" width="100%">
              <thead>
                <tr>
                  <th>Enviado por</th>
                  <th>Título</th>
                  <th>Descrição</th>
                  <th>Autor</th>
                  <th>Aprovado?</th>
                  <th>Data defesa</th>
                  <th>Tese/Dissertação</th>
                  <th>Mestrado/Doutorado</th>
                  <th>Download</th>
                  <th>Ver</th>
                  <th>Editar</th>
                  <th>Deletar</th>
                </tr>
              </thead>
            
              <tbody>
                <% @documentos.each do |documento| %>
                  <tr>
                    <td>
                      <% if documento.user %>
                        <%= documento.user.name %>
                      <% end %>
                    </td>
                    <td><%= documento.titulo %></td>
                    <td><%= documento.descricao %></td>
                    <td><%= documento.author %></td>
                    <td>
                      <% if documento.accepted %>
                        <%= "Aprovado" %>
                      <% else %>
                        <% if documento.respondido %>
                          <%= "Reprovado" %>
                        <% else %>
                          <%= "Ainda não respondido" %>
                        <% end %>
                      <% end %>
                    </td>
                    <td><%= imprime_data(documento.data_defesa, 0) %></td>
                    <td>
                      <% if documento.tese %>
                        <%= "Tese" %>
                      <% else %>
                        <%= "Dissertação" %>
                      <% end %>
                    </td>
                    <td>
                      <% if documento.mestrado %>
                        <%= "Mestrado" %>
                      <% else %>
                        <%= "Doutorado" %>
                      <% end %>
                    </td>
                    <td><%= link_to "Download", documento.arquivo_url %></td>
                    <td><%= link_to 'Ver', documento %></td>
                    <td><%= link_to 'Editar', edit_documento_path(documento) %></td>
                    <td><%= link_to 'Deletar', documento, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            </div>
        </div>
        <div class="pst-button">
          <button><%= link_to 'Novo Documento', new_documento_path %></button>
        </div>
      </div>
    </div>  
  </div>
  <%= render 'layouts/footer' %>
</div>
            
            

app/views/documentos/new.html.erb
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Novo Documento</h2>
      <div class="pst-container">
        <div class="pst-content">
          <%= render 'form', documento: @documento %>
        </div>
        <div class="pst-button">
          <%= link_to 'Voltar', documentos_path %>
        </div>
      </div>
    </div>  
  </div>
  <%= render 'layouts/footer' %>
</div>

app/views/documentos/show.html.erb
<div class="pst-corpo-main-container">
  <div class="pst-main-container">
    <div class="main clearfix">
      <h2>Documento</h2>
      <div class="pst-container">
        <div class="pst-content">
          <div class="pst-info-content">
            <p>
              <strong>User:</strong>
              <% if @documento.user %>
                <%= @documento.user.name %>
              <% end %> 
            </p>
            
            <p>
              <strong>Titulo:</strong>
              <%= @documento.titulo %>
            </p>
            
            <p>
              <strong>Descricao:</strong>
              <%= @documento.descricao %>
            </p>
            
            <p>
              <strong>Status:</strong>
              <% if @documento.accepted %>
                <%= "Aprovado" %>
              <% else %>
                <% if @documento.respondido %>
                  <%= "Reprovado" %>
                <% else %>
                  <%= "Pendente" %>
                <% end %>
              <% end %>
            </p>
            
            <p>
              <strong>Data defesa:</strong>
              <%= imprime_data(@documento.data_defesa) %>
            </p>
            
            <p>
              <strong>Tese:</strong>
              <% if @documento.tese %>
                <%= "Tese" %>
              <% else %>
                <%= "Dissertação" %>
              <% end %>
            </p>
            
            <p>
              <strong>Mestrado:</strong>
              <%if @documento.mestrado %>
                <%= "Mestrado" %>
              <% else %>
                <%= "Doutorado" %>
              <% end %>
            </p>
            
            <div class="pst-button">
              <%= link_to 'Edit', edit_documento_path(@documento) %> |
              <%= link_to 'Back', documentos_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</div>  