config/routes.rb
Rails.application.routes.draw do
  resources :documentos_simposios
  resources :videos_simposios
  resources :simposios
  resources :eventos
  resources :documentos
  
  
  get 'password_resets/new'

  get 'password_resets/edit'

  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  get 'sessions/new'

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users
  resources :account_activations, only: [:edit]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  post '/lostemail', to: 'users#lostemail'
  
  patch 'editemailupdate' => 'users#editemailupdate'
  patch 'editpasswordupdate' => 'users#editpasswordupdate'
  
  patch 'addvideo' => 'videos_simposios#addvideo'
  patch 'adddoc' => 'documentos_simposios#adddoc'
  
  get 'dashboard' => 'pages#dashboard'
  get 'users_simposios' => 'pages#simposios'
  get 'user_aprove_image' => 'users#aprove_user_image'
  get 'aceitar_foto' => 'pages#aprovacao_imagens'
  get 'aceitar_doc' => 'documentos#aceitar_doc'
  get 'aprove_doc' => 'documentos#aprove_doc'
  get 'fotos' => 'users#fotos'
  get 'arquivo_show' => 'pages#arquivo_show'
  get 'editemail' => 'users#editemail'
  get 'editpassword' => 'users#editpassword'
  get 'recuperacao' => 'pages#recuperacao'
  get 'publicacoes'    => 'pages#publicacoes'
  get 'arquivos' => 'pages#arquivos'
  get 'tese_view' => 'pages#tese_view'
  get 'linhasdepesquisa'    => 'pages#linhasdepesquisa'
  get 'painel'    => 'pages#painel'
  get 'teses'    => 'pages#teses'
  get 'parceiros'    => 'pages#parceiros'
  get 'colaboradores' => 'pages#colaboradores'
  get 'instituicoes'  => 'pages#instituicoes'
  get 'events'    => 'pages#eventos'
  get 'coordenadores'    => 'pages#coordenadores'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer-container">
    <div class="row">
        <div class= "copyright col-lg-8 col-md-8 col-sm-8 col-xs-12">
           <p>Copyright &#169; 2016 - LABPEC todos os direitos reservados</p> 
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <div class="des-in">
                <p> Desenvolvido por: <br></p> 
                <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-3"></div>
                <div class="n-photo col-lg-4 col-md-4 col-sm-4 col-xs-6">
                    <a href=""><%= image_tag("logoin.png", class: 'logoIN img-responsive') %></a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-3"></div>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header-admin.html.erb
<div class="header-main-container">
    <header class="header-container">
        <div class="row">
            <div class="logo-container">
                <a href="/"><%= image_tag("logo.png", class: 'logo1 img-responsive') %></a>  
            </div>
        </div>    
    </header>
    <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav nav-a navbar-left">
                <li><%= link_to "Slides", root_path %></li>
                <li><%= link_to "Usuários",    linhasdepesquisa_path %></li>
                <li><%= link_to "Teses e dissertações",    teses_path %></li>
                <li><%= link_to "Publicações",    publicacoes_path %></li>
                <li><%= link_to "Eventos",    eventos_path %></li>
              </ul>
              
            </div><!--/.nav-collapse -->
          </div>
    </nav>
</div>

app/views/layouts/_header-no-menu.html.erb
<div class="header-main-container">
    <header class="header-container">
        <div class="row">
            <div class="logo-container">
                <a href="/"><%= image_tag("logo.png", class: 'logo1 img-responsive') %></a>  
            </div>
        </div> 
    </header>
    <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav nav-a navbar-left">
                <li><%= link_to "Página Inicial", root_path %></li>
              </ul>
              <ul class="nav navbar-nav nav-a navbar-right">
                <li><%= link_to "Manual",    linhasdepesquisa_path %></li>
                <li><%= link_to "Sair",    logout_url %></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
    </nav>
</div>

app/views/layouts/_header.html.erb
<div class="header-main-container">
    <header class="header-container">
        <div class="row">
            <div class="logo-container">
                <a href="/"><%= image_tag("logo.png", class: 'logo1 img-responsive') %></a>  
            </div>
        </div>    
    </header>
    <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav nav-a">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Quem Somos",    coordenadores_path %></li>
                <li><%= link_to "Linhas de pesquisa",    linhasdepesquisa_path %></li>
                <li><%= link_to "Teses e dissertações",    teses_path %></li>
                <li><%= link_to "Publicações",    publicacoes_path %></li>
                <li><%= link_to "Eventos",    events_path %></li>
                <li><%= link_to "Parceiros",    colaboradores_path %></li>
                   <% if logged_in? %>
                     <li><%= link_to current_user.name, edit_user_path(current_user) %> </li>
                     <li><%= link_to 'Sair', logout_url %> </li>
                    <% else %>
                      <li><%= link_to 'Entrar', login_url %></li>
                   <% end %>
              </ul>
              
            </div><!--/.nav-collapse -->
          </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- rails server -b $IP -p $PORT -->
<html>
  <head>
    
    <meta charset = "utf-8" >
    <meta http-equiv = "X-UA-Compatible" content = "IE=edge" >
    <meta name = "viewport" content = "width=device-width, initial-scale=1" >
    <meta name="description" content="LABPEC - Laboratório de pesquisa em Estudos de Linguagem">
    <meta name="keywords" content="LABPEC, Linguagem, Estudos, UFF, Laboratório">
    <meta name="author" content="InJunior">
    
    <title><%= yield(:title) %> | Conheça o LABPEC</title>
    <link rel="shortcut icon" type="image/png" href="/assets/Logo.png"/>
    
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    
    <section class="pag-container" id="topo">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <% if request.path != "/login" && !current_page?(painel_path) %>
          <% if administrador? %>
            <% if !current_page?(root_path) && !current_page?(publicacoes_path) && !current_page?(teses_path) && !current_page?(linhasdepesquisa_path) && !current_page?(eventos_path) && !current_page?(colaboradores_path) && !current_page?(instituicoes_path) && !current_page?(arquivos_path) && !current_page?(arquivo_show_path)%>
              <% if current_page?(dashboard_path) %>
                <%= render 'layouts/header-no-menu' %>
              <% else %>
                <%= render 'layouts/header-admin' %>
              <% end %>
            <% else %>
              <%= render 'layouts/header' %>
            <% end %>  
          <% else %>
            <%= render 'layouts/header' %>
          <% end %>
        <% end %>
        <%= yield %>
        <%# debug(params) if Rails.env.development? %>
        
    </section>
    
    
     
    
    
    <!-- Initialize Swiper -->
    <script type="text/javascript">
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        paginationClickable: true,
        spaceBetween: 30,
        centeredSlides: true,
        autoplay: 2500,
        autoplayDisableOnInteraction: false
    });
    </script>
    
    
    
    <!---------DATA TABLES----------------->
    
    <script type="text/javascript">
		  $("#tablesorter").DataTable({
		        "lengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
		        	language:{
              		info: "Mostrando de _START_ até _END_ de _TOTAL_ registros.",
              		search: "Pesquisar ",
              		paginate:{
              			next: "Próxima",
              			previous: "Anterior",
              			first: "Primeira página",
              			last: "Última página"
              		},
              		lengthMenu: "_MENU_ resultados por página",
              		emptyTable: "Nenhum registro foi encontrado",
              		zeroRecords: "Nenhum registro foi encontrado",	
            	}
		    });
	  </script>
	  
	  
	  <!-- Scripts para não precisarmos atualizar a pagina toda vez que alterarmos algum dado -->
	  <script type="text/javascript">
       <%= yield :js %>
    </script>
	
  </body>
</html>